project_id = "xuukkofrvxhxqspmltlj"

[functions.generate-pitch]
verify_jwt = false

[functions.static-map-proxy]
verify_jwt = false

[functions.import-popety]
verify_jwt = false

[functions.parse-strava-screenshot]
verify_jwt = false

[functions.uniqode-qr]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false
